version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/types"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/x/data"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/x/ecocredit"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
