#
# Codecov Docs:
# https://docs.codecov.com/docs
#
# Codecov Report:
# https://app.codecov.io/gh/regen-network/regen-ledger
#
coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        target: 80%
        threshold: 1%
      app:
        paths:
          - "app/"
      data:
        paths:
          - "x/data/"
      ecocredit:
        paths:
          - "x/ecocredit/"
      types:
        paths:
          - "types/"
    changes: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "contrib"
  - "docs"
  - "scripts"
  - "**/simulation"
  - "**/*.cosmos_orm.go"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "statik.go"
