run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # TODO: consider enabling and resolving
    # - wsl

issues:
  exclude-rules:
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

linters-settings:
  dogsled:
    max-blank-identifiers: 3
