project_name: regen-ledger

before:
  hooks:
    - ./scripts/completions.sh

env:
  - GO111MODULE=on

builds:
  - id: regen-darwin-amd64
    binary: regen
    main: ./cmd/regen
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/target/bin/o64-clang++
      - LD_LIBRARY_PATH=/home/runner/work/osxcross/target/binaries/lib
    flags:
      - -mod=readonly
      - -tags="netgo ledger"
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=regen
      - -X github.com/cosmos/cosmos-sdk/version.AppName=regen
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

  - id: regen-darwin-arm64
    binary: regen
    main: ./cmd/regen
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - LD_LIBRARY_PATH=/home/runner/work/osxcross/target/binaries/lib
    flags:
      - -mod=readonly
      - -tags="netgo ledger"
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=regen
      - -X github.com/cosmos/cosmos-sdk/version.AppName=regen
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

  - id: regen-linux-amd64
    binary: regen
    main: ./cmd/regen
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -mod=readonly
      - -tags="netgo ledger"
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=regen
      - -X github.com/cosmos/cosmos-sdk/version.AppName=regen
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

  - id: regen-linux-arm64
    binary: regen
    main: ./cmd/regen
    goarch:
      - arm64
    goos:
      - linux
    flags:
      - -mod=readonly
      - -tags="netgo ledger"
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=regen
      - -X github.com/cosmos/cosmos-sdk/version.AppName=regen
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

  - id: regen-windows-amd64
    binary: regen
    main: ./cmd/regen
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows
    flags:
      - -mod=readonly
      - -tags="netgo ledger"
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=regen
      - -X github.com/cosmos/cosmos-sdk/version.AppName=regen
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

archives:
  - id: regen
    builds:
      - regen-darwin-amd64
      - regen-darwin-arm64
      - regen-linux-amd64
      - regen-linux-arm64
      - regen-windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

brews:
  - name: regen-ledger
    ids: 
      - regen
    tap:
      owner: regen-network
      name: regen-ledger
      branch: homebrew-taps
    folder: "{{ .Tag }}"
    homepage: "https://www.regen.network/"
    description: "Blockchain-powered marketplace for climate solutions and planetary regenerations"
    test: |
      system "#{bin}/regen --version"
    install: |
      bin.install "regen"
      bash_completion.install "completions/regen.bash" => "regen"
      zsh_completion.install "completions/regen.zsh" => "_regen"
      fish_completion.install "completions/regen.fish"  

nfpms:
  - maintainer: regen-network
    description: "Blockchain-powered marketplace for climate solutions and planetary regenerations"
    homepage: "https://www.regen.network/"
    license: Apache2.0
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./completions/regen.bash
        dst: /usr/share/bash-completion/completions/regen
        file_info:
          mode: 0644
      - src: ./completions/regen.fish
        dst: /usr/share/fish/vendor_completions.d/regen.fish
        file_info:
          mode: 0644
      - src: ./completions/regen.zsh
        dst:  /usr/share/zsh/vendor-completions/_regen
        file_info:
          mode: 0644

release:
  github:
    owner: regen-network
    name: regen-ledger
  prerelease: auto
  draft: false
