project_name: regen-ledger

before:
  hooks:
    - ./scripts/completions.sh
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - COSMWASM_VERSION={{ .Env.COSMWASM_VERSION }}

builds:

  - id: regen-linux-amd64
    binary: regen
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/libwasmvm_muslc.x86_64.a
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/checksums.txt -O /tmp/checksums.txt
        - sha256sum /usr/lib/libwasmvm_muslc.x86_64.a | grep $(grep libwasmvm_muslc.x86_64.a /tmp/checksums.txt | awk '{print $1}')
        - ln -sf /usr/lib/libwasmvm_muslc.x86_64.a /usr/lib/libwasmvm.x86_64.a
    main: ./cmd/regen
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-L/usr/lib -lwasmvm_muslc.x86_64 -Wl,-z,muldefs -lm -lc -lrt -lpthread"

  - id: regen-linux-arm64
    binary: regen
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/libwasmvm_muslc.aarch64.a
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/checksums.txt -O /tmp/checksums.txt
        - sha256sum /usr/lib/libwasmvm_muslc.aarch64.a | grep $(grep libwasmvm_muslc.aarch64.a /tmp/checksums.txt | awk '{print $1}')
        - ln -sf /usr/lib/libwasmvm_muslc.aarch64.a /usr/lib/libwasmvm.aarch64.a
        - go mod download
    main: ./cmd/regen
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-L/usr/lib -lwasmvm_muslc.aarch64 -Wl,-z,muldefs -lm -lc -lrt -lpthread"

archives:
  - id: regen
    builds:
      - regen-linux-amd64
      - regen-linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - completions*
      - README.md
      - LICENSE


nfpms:
  - maintainer: regen-network
    description: "Blockchain-powered marketplace for climate solutions and planetary regenerations"
    homepage: "https://www.regen.network/"
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./completions/regen.bash
        dst: /usr/share/bash-completion/completions/regen
        file_info:
          mode: 0644
      - src: ./completions/regen.fish
        dst: /usr/share/fish/vendor_completions.d/regen.fish
        file_info:
          mode: 0644
      - src: ./completions/regen.zsh
        dst:  /usr/share/zsh/vendor-completions/_regen
        file_info:
          mode: 0644

release:
  github:
    owner: regen-network
    name: regen-ledger
  prerelease: auto
  draft: false
