version: "3"

services:
  regen-node-0:
    container_name: regen-node-0
    image: "regen-ledger/regen-env"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-regen.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./.localnet:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  regen-node-1:
    container_name: regen-node-1
    image: "regen-ledger/regen-env"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - DEBUG=1
      - ID=1
      - LOG=${LOG:-regen.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./.localnet:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  regen-node-2:
    container_name: regen-node-2
    image: "regen-ledger/regen-env"
    environment:
      - DEBUG=1
      - ID=2
      - LOG=${LOG:-regen.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./.localnet:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  regen-node-3:
    container_name: regen-node-3
    image: "regen-ledger/regen-env"
    environment:
      - DEBUG=1
      - ID=3
      - LOG=${LOG:-regen.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./.localnet:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
