// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: regen/data/v1/tx.proto

package data

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgAnchor is the Msg/Anchor request type.
type MsgAnchor struct {
	// sender is the address of the sender of the transaction. The sender in
	// Anchor is not attesting to the veracity of the underlying data. They
	// can simply be an intermediary providing services.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// hash is the content hash for the data to anchor.
	Hash *ContentHash `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *MsgAnchor) Reset()         { *m = MsgAnchor{} }
func (m *MsgAnchor) String() string { return proto.CompactTextString(m) }
func (*MsgAnchor) ProtoMessage()    {}
func (*MsgAnchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{0}
}
func (m *MsgAnchor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchor.Merge(m, src)
}
func (m *MsgAnchor) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchor proto.InternalMessageInfo

func (m *MsgAnchor) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAnchor) GetHash() *ContentHash {
	if m != nil {
		return m.Hash
	}
	return nil
}

// MsgAnchor is the Msg/Anchor response type.
type MsgAnchorResponse struct {
	// iri is the IRI of the data that was anchored.
	Iri string `protobuf:"bytes,1,opt,name=iri,proto3" json:"iri,omitempty"`
	// timestamp is the timestamp at which the data was anchored.
	Timestamp *types.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *MsgAnchorResponse) Reset()         { *m = MsgAnchorResponse{} }
func (m *MsgAnchorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorResponse) ProtoMessage()    {}
func (*MsgAnchorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{1}
}
func (m *MsgAnchorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorResponse.Merge(m, src)
}
func (m *MsgAnchorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorResponse proto.InternalMessageInfo

func (m *MsgAnchorResponse) GetIri() string {
	if m != nil {
		return m.Iri
	}
	return ""
}

func (m *MsgAnchorResponse) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// MsgAttest is the Msg/Attest request type.
type MsgAttest struct {
	// attestor is the addresses of the account attesting to the veracity of the
	// data. By making an Attest request, the attestor is attesting to the
	// veracity of the data referenced by the IRI. The precise meaning of this may
	// vary depending on the underlying data.
	Attestor string `protobuf:"bytes,1,opt,name=attestor,proto3" json:"attestor,omitempty"`
	// hashes are the content hashes for anchored data. Only RDF graph data can be
	// signed as its data model is intended to specifically convey semantic
	// meaning.
	Hashes []*ContentHash_Graph `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
}

func (m *MsgAttest) Reset()         { *m = MsgAttest{} }
func (m *MsgAttest) String() string { return proto.CompactTextString(m) }
func (*MsgAttest) ProtoMessage()    {}
func (*MsgAttest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{2}
}
func (m *MsgAttest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttest.Merge(m, src)
}
func (m *MsgAttest) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttest proto.InternalMessageInfo

func (m *MsgAttest) GetAttestor() string {
	if m != nil {
		return m.Attestor
	}
	return ""
}

func (m *MsgAttest) GetHashes() []*ContentHash_Graph {
	if m != nil {
		return m.Hashes
	}
	return nil
}

// MsgAttestResponse is the Msg/Attest response type.
type MsgAttestResponse struct {
	// new_entries are the new attestor entries including the attestor, the IRI,
	// and the timestamp. If the attestor attests to the same piece of data, the
	// entry will not be updated and not included in the response.
	NewEntries []*AttestorEntry `protobuf:"bytes,1,rep,name=new_entries,json=newEntries,proto3" json:"new_entries,omitempty"`
}

func (m *MsgAttestResponse) Reset()         { *m = MsgAttestResponse{} }
func (m *MsgAttestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAttestResponse) ProtoMessage()    {}
func (*MsgAttestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{3}
}
func (m *MsgAttestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestResponse.Merge(m, src)
}
func (m *MsgAttestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestResponse proto.InternalMessageInfo

func (m *MsgAttestResponse) GetNewEntries() []*AttestorEntry {
	if m != nil {
		return m.NewEntries
	}
	return nil
}

// MsgDefineResolver is the Msg/DefineResolver request type.
type MsgDefineResolver struct {
	// manager is the address of the resolver manager. The manager is able
	// to make future calls using the ID returned by this operation with
	// Msg/RegisterResolver. To authorize other accounts to register resolvers,
	// the manager should make use of cosmos.authz.
	Manager string `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	// resolver_url is a resolver URL which should refer to an HTTP service
	// which will respond to a GET request with the IRI of a ContentHash
	// and return the content if it exists or a 404. For graph data, resolvers
	// should use the HTTP Accept header to negotiate the RDF serialization
	// format.
	ResolverUrl string `protobuf:"bytes,2,opt,name=resolver_url,json=resolverUrl,proto3" json:"resolver_url,omitempty"`
}

func (m *MsgDefineResolver) Reset()         { *m = MsgDefineResolver{} }
func (m *MsgDefineResolver) String() string { return proto.CompactTextString(m) }
func (*MsgDefineResolver) ProtoMessage()    {}
func (*MsgDefineResolver) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{4}
}
func (m *MsgDefineResolver) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDefineResolver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDefineResolver.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDefineResolver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDefineResolver.Merge(m, src)
}
func (m *MsgDefineResolver) XXX_Size() int {
	return m.Size()
}
func (m *MsgDefineResolver) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDefineResolver.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDefineResolver proto.InternalMessageInfo

func (m *MsgDefineResolver) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *MsgDefineResolver) GetResolverUrl() string {
	if m != nil {
		return m.ResolverUrl
	}
	return ""
}

// MsgDefineResolverResponse is the Msg/DefineResolver response type.
type MsgDefineResolverResponse struct {
	// resolver_id is the integer ID of the resolver to be used in
	// MsgRegisterResolver.
	ResolverId uint64 `protobuf:"varint,1,opt,name=resolver_id,json=resolverId,proto3" json:"resolver_id,omitempty"`
}

func (m *MsgDefineResolverResponse) Reset()         { *m = MsgDefineResolverResponse{} }
func (m *MsgDefineResolverResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDefineResolverResponse) ProtoMessage()    {}
func (*MsgDefineResolverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{5}
}
func (m *MsgDefineResolverResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDefineResolverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDefineResolverResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDefineResolverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDefineResolverResponse.Merge(m, src)
}
func (m *MsgDefineResolverResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDefineResolverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDefineResolverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDefineResolverResponse proto.InternalMessageInfo

func (m *MsgDefineResolverResponse) GetResolverId() uint64 {
	if m != nil {
		return m.ResolverId
	}
	return 0
}

// MsgRegisterResolver is the Msg/RegisterResolver request type.
type MsgRegisterResolver struct {
	// manager is the address of the resolver manager who registered this
	// resolver with Msg/DefinedResolver.
	Manager string `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	// resolver_id is the ID of a resolver defined with Msg/DefineResolver.
	ResolverId uint64 `protobuf:"varint,2,opt,name=resolver_id,json=resolverId,proto3" json:"resolver_id,omitempty"`
	// data is a list of content hashes which the resolver claims to serve.
	Data []*ContentHash `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (m *MsgRegisterResolver) Reset()         { *m = MsgRegisterResolver{} }
func (m *MsgRegisterResolver) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterResolver) ProtoMessage()    {}
func (*MsgRegisterResolver) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{6}
}
func (m *MsgRegisterResolver) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterResolver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterResolver.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterResolver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterResolver.Merge(m, src)
}
func (m *MsgRegisterResolver) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterResolver) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterResolver.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterResolver proto.InternalMessageInfo

func (m *MsgRegisterResolver) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *MsgRegisterResolver) GetResolverId() uint64 {
	if m != nil {
		return m.ResolverId
	}
	return 0
}

func (m *MsgRegisterResolver) GetData() []*ContentHash {
	if m != nil {
		return m.Data
	}
	return nil
}

// MsgRegisterResolverResponse is the Msg/RegisterResolver response type.
type MsgRegisterResolverResponse struct {
}

func (m *MsgRegisterResolverResponse) Reset()         { *m = MsgRegisterResolverResponse{} }
func (m *MsgRegisterResolverResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterResolverResponse) ProtoMessage()    {}
func (*MsgRegisterResolverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87f072557099c45, []int{7}
}
func (m *MsgRegisterResolverResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterResolverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterResolverResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterResolverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterResolverResponse.Merge(m, src)
}
func (m *MsgRegisterResolverResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterResolverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterResolverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterResolverResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgAnchor)(nil), "regen.data.v1.MsgAnchor")
	proto.RegisterType((*MsgAnchorResponse)(nil), "regen.data.v1.MsgAnchorResponse")
	proto.RegisterType((*MsgAttest)(nil), "regen.data.v1.MsgAttest")
	proto.RegisterType((*MsgAttestResponse)(nil), "regen.data.v1.MsgAttestResponse")
	proto.RegisterType((*MsgDefineResolver)(nil), "regen.data.v1.MsgDefineResolver")
	proto.RegisterType((*MsgDefineResolverResponse)(nil), "regen.data.v1.MsgDefineResolverResponse")
	proto.RegisterType((*MsgRegisterResolver)(nil), "regen.data.v1.MsgRegisterResolver")
	proto.RegisterType((*MsgRegisterResolverResponse)(nil), "regen.data.v1.MsgRegisterResolverResponse")
}

func init() { proto.RegisterFile("regen/data/v1/tx.proto", fileDescriptor_c87f072557099c45) }

var fileDescriptor_c87f072557099c45 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xa4, 0x0a, 0x64, 0x02, 0xa8, 0x18, 0xa9, 0x72, 0x0d, 0xb8, 0xc1, 0xa7, 0x08,
	0x81, 0xad, 0x86, 0x4b, 0x0f, 0x70, 0x28, 0xb4, 0xfc, 0x39, 0x44, 0x42, 0x0b, 0x5c, 0x10, 0x52,
	0xe4, 0x34, 0xd3, 0xb5, 0x45, 0xb2, 0x6b, 0xed, 0x6e, 0x92, 0xf6, 0xc6, 0x23, 0xf0, 0x58, 0x1c,
	0x2b, 0x71, 0xe1, 0x88, 0x92, 0x17, 0x41, 0x5e, 0xdb, 0x8b, 0xe2, 0xa4, 0xcd, 0xcd, 0x33, 0xf3,
	0xed, 0x6f, 0xbf, 0x99, 0x9d, 0x04, 0xf6, 0x04, 0x52, 0x64, 0xe1, 0x28, 0x52, 0x51, 0x38, 0x3b,
	0x0c, 0xd5, 0x45, 0x90, 0x0a, 0xae, 0xb8, 0x7d, 0x57, 0xe7, 0x83, 0x2c, 0x1f, 0xcc, 0x0e, 0xdd,
	0x03, 0xca, 0x39, 0x1d, 0x63, 0xa8, 0x8b, 0xc3, 0xe9, 0x79, 0xa8, 0x92, 0x09, 0x4a, 0x15, 0x4d,
	0xd2, 0x5c, 0xef, 0xee, 0x57, 0x38, 0x97, 0x29, 0xca, 0xbc, 0xe4, 0x7f, 0x82, 0x56, 0x5f, 0xd2,
	0x63, 0x76, 0x16, 0x73, 0x61, 0xef, 0x41, 0x53, 0x22, 0x1b, 0xa1, 0x70, 0xac, 0x8e, 0xd5, 0x6d,
	0x91, 0x22, 0xb2, 0x03, 0xd8, 0x89, 0x23, 0x19, 0x3b, 0xf5, 0x8e, 0xd5, 0x6d, 0xf7, 0xdc, 0x60,
	0xe5, 0xfa, 0xe0, 0x0d, 0x67, 0x0a, 0x99, 0x7a, 0x1f, 0xc9, 0x98, 0x68, 0x9d, 0x3f, 0x80, 0xfb,
	0x06, 0x4a, 0x50, 0xa6, 0x9c, 0x49, 0xb4, 0x77, 0xa1, 0x91, 0x88, 0xa4, 0x20, 0x67, 0x9f, 0xf6,
	0x11, 0xb4, 0x8c, 0x53, 0xc3, 0xce, 0x7b, 0x09, 0xca, 0x5e, 0x82, 0xcf, 0xa5, 0x82, 0xfc, 0x17,
	0xfb, 0x51, 0xee, 0x5a, 0x29, 0x94, 0xca, 0x76, 0xe1, 0x76, 0xa4, 0xbf, 0x78, 0xe9, 0xdb, 0xc4,
	0xf6, 0x11, 0x34, 0x33, 0x47, 0x28, 0x9d, 0x7a, 0xa7, 0xd1, 0x6d, 0xf7, 0x3a, 0xd7, 0x7b, 0x0f,
	0xde, 0x89, 0x28, 0x8d, 0x49, 0xa1, 0xf7, 0x49, 0xde, 0x83, 0x06, 0x99, 0x1e, 0x5e, 0x41, 0x9b,
	0xe1, 0x7c, 0x80, 0x4c, 0x89, 0x04, 0xa5, 0x63, 0x69, 0xe6, 0xa3, 0x0a, 0xf3, 0xb8, 0xb8, 0xfc,
	0x94, 0x29, 0x71, 0x49, 0x80, 0xe1, 0xfc, 0x34, 0xd7, 0xfb, 0x1f, 0x35, 0xf3, 0x04, 0xcf, 0x13,
	0x86, 0x04, 0x25, 0x1f, 0xcf, 0x50, 0xd8, 0x0e, 0xdc, 0x9a, 0x44, 0x2c, 0xa2, 0x66, 0xea, 0x65,
	0x68, 0x3f, 0x81, 0x3b, 0xa2, 0x50, 0x0d, 0xa6, 0x62, 0xac, 0x47, 0xd4, 0x22, 0xed, 0x32, 0xf7,
	0x45, 0x8c, 0xfd, 0x97, 0xb0, 0xbf, 0x46, 0x34, 0x6e, 0x0f, 0xc0, 0x68, 0x07, 0xc9, 0x48, 0xd3,
	0x77, 0x08, 0x94, 0xa9, 0x0f, 0x23, 0xff, 0x87, 0x05, 0x0f, 0xfa, 0x92, 0x12, 0xa4, 0x89, 0x54,
	0xfa, 0xe0, 0x36, 0x4b, 0x15, 0x64, 0xbd, 0x8a, 0xcc, 0x56, 0x25, 0x9b, 0x83, 0xd3, 0xd0, 0xa3,
	0xb9, 0x71, 0x55, 0xb2, 0xa4, 0xff, 0x18, 0x1e, 0x6e, 0x70, 0x50, 0xb6, 0xd0, 0xfb, 0x5d, 0x87,
	0x46, 0x5f, 0x52, 0xfb, 0x04, 0x9a, 0xc5, 0x8e, 0x3a, 0x15, 0xa4, 0x59, 0x34, 0xb7, 0x73, 0x5d,
	0xc5, 0x0c, 0x24, 0xa3, 0xe4, 0x3b, 0xb3, 0x89, 0xa2, 0x2b, 0x1b, 0x29, 0xab, 0x4b, 0xf0, 0x0d,
	0xee, 0x55, 0x9e, 0x70, 0xc3, 0x99, 0x55, 0x85, 0xdb, 0xdd, 0xa6, 0x30, 0xf4, 0x21, 0xec, 0xae,
	0xbd, 0x87, 0xbf, 0x7e, 0xba, 0xaa, 0x71, 0x9f, 0x6e, 0xd7, 0x94, 0x77, 0xbc, 0x7e, 0xfb, 0x6b,
	0xe1, 0x59, 0x57, 0x0b, 0xcf, 0xfa, 0xbb, 0xf0, 0xac, 0x9f, 0x4b, 0xaf, 0x76, 0xb5, 0xf4, 0x6a,
	0x7f, 0x96, 0x5e, 0xed, 0xeb, 0x33, 0x9a, 0xa8, 0x78, 0x3a, 0x0c, 0xce, 0xf8, 0x24, 0xd4, 0xbc,
	0xe7, 0x0c, 0xd5, 0x9c, 0x8b, 0xef, 0x45, 0x34, 0xc6, 0x11, 0x45, 0x11, 0x5e, 0xe8, 0xff, 0x92,
	0x61, 0x53, 0xff, 0x4a, 0x5f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xf7, 0xdd, 0x70, 0xa8,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Anchor "anchors" a piece of data to the blockchain based on its secure
	// hash, effectively providing a tamper resistant timestamp.
	//
	// The sender in Anchor is not attesting to the veracity of the underlying
	// data. They can simply be an intermediary providing timestamp services.
	// Attest should be used to create a digital signature attesting to the
	// veracity of some piece of data.
	Anchor(ctx context.Context, in *MsgAnchor, opts ...grpc.CallOption) (*MsgAnchorResponse, error)
	// Attest allows for digital signing of an arbitrary piece of data on the
	// blockchain. By attesting to data, the attestor is making a statement about
	// the veracity of the data itself. It is like signing a legal document,
	// meaning that I agree to all conditions and to the best of my knowledge
	// everything is true. When anchoring data, the sender is not attesting to the
	// veracity of the data, they are simply communicating that it exists.
	//
	// On-chain signatures have the following benefits:
	// - on-chain identities can be managed using different cryptographic keys
	//   that change over time through key rotation practices
	// - an on-chain identity may represent an organization and through delegation
	//   individual members may sign on behalf of the group
	// - the blockchain transaction envelope provides built-in replay protection
	//   and timestamping
	//
	// Attest implicitly calls Anchor if the data was not already anchored.
	//
	// Attest can be called multiple times for the same content hash with
	// different attestors and those attestors will be appended to the list of
	// attestors. If the same attestor attempts to attest to the same piece of
	// data, the attestor will be ignored and a new attestation with a new
	// timestamp will not be added.
	Attest(ctx context.Context, in *MsgAttest, opts ...grpc.CallOption) (*MsgAttestResponse, error)
	// DefineResolver defines a resolver URL and assigns it a new integer ID
	// that can be used in calls to RegisterResolver.
	DefineResolver(ctx context.Context, in *MsgDefineResolver, opts ...grpc.CallOption) (*MsgDefineResolverResponse, error)
	// RegisterResolver registers data content hashes
	RegisterResolver(ctx context.Context, in *MsgRegisterResolver, opts ...grpc.CallOption) (*MsgRegisterResolverResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Anchor(ctx context.Context, in *MsgAnchor, opts ...grpc.CallOption) (*MsgAnchorResponse, error) {
	out := new(MsgAnchorResponse)
	err := c.cc.Invoke(ctx, "/regen.data.v1.Msg/Anchor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Attest(ctx context.Context, in *MsgAttest, opts ...grpc.CallOption) (*MsgAttestResponse, error) {
	out := new(MsgAttestResponse)
	err := c.cc.Invoke(ctx, "/regen.data.v1.Msg/Attest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DefineResolver(ctx context.Context, in *MsgDefineResolver, opts ...grpc.CallOption) (*MsgDefineResolverResponse, error) {
	out := new(MsgDefineResolverResponse)
	err := c.cc.Invoke(ctx, "/regen.data.v1.Msg/DefineResolver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterResolver(ctx context.Context, in *MsgRegisterResolver, opts ...grpc.CallOption) (*MsgRegisterResolverResponse, error) {
	out := new(MsgRegisterResolverResponse)
	err := c.cc.Invoke(ctx, "/regen.data.v1.Msg/RegisterResolver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Anchor "anchors" a piece of data to the blockchain based on its secure
	// hash, effectively providing a tamper resistant timestamp.
	//
	// The sender in Anchor is not attesting to the veracity of the underlying
	// data. They can simply be an intermediary providing timestamp services.
	// Attest should be used to create a digital signature attesting to the
	// veracity of some piece of data.
	Anchor(context.Context, *MsgAnchor) (*MsgAnchorResponse, error)
	// Attest allows for digital signing of an arbitrary piece of data on the
	// blockchain. By attesting to data, the attestor is making a statement about
	// the veracity of the data itself. It is like signing a legal document,
	// meaning that I agree to all conditions and to the best of my knowledge
	// everything is true. When anchoring data, the sender is not attesting to the
	// veracity of the data, they are simply communicating that it exists.
	//
	// On-chain signatures have the following benefits:
	// - on-chain identities can be managed using different cryptographic keys
	//   that change over time through key rotation practices
	// - an on-chain identity may represent an organization and through delegation
	//   individual members may sign on behalf of the group
	// - the blockchain transaction envelope provides built-in replay protection
	//   and timestamping
	//
	// Attest implicitly calls Anchor if the data was not already anchored.
	//
	// Attest can be called multiple times for the same content hash with
	// different attestors and those attestors will be appended to the list of
	// attestors. If the same attestor attempts to attest to the same piece of
	// data, the attestor will be ignored and a new attestation with a new
	// timestamp will not be added.
	Attest(context.Context, *MsgAttest) (*MsgAttestResponse, error)
	// DefineResolver defines a resolver URL and assigns it a new integer ID
	// that can be used in calls to RegisterResolver.
	DefineResolver(context.Context, *MsgDefineResolver) (*MsgDefineResolverResponse, error)
	// RegisterResolver registers data content hashes
	RegisterResolver(context.Context, *MsgRegisterResolver) (*MsgRegisterResolverResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Anchor(ctx context.Context, req *MsgAnchor) (*MsgAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Anchor not implemented")
}
func (*UnimplementedMsgServer) Attest(ctx context.Context, req *MsgAttest) (*MsgAttestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (*UnimplementedMsgServer) DefineResolver(ctx context.Context, req *MsgDefineResolver) (*MsgDefineResolverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefineResolver not implemented")
}
func (*UnimplementedMsgServer) RegisterResolver(ctx context.Context, req *MsgRegisterResolver) (*MsgRegisterResolverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterResolver not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Anchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnchor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Anchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.data.v1.Msg/Anchor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Anchor(ctx, req.(*MsgAnchor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.data.v1.Msg/Attest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Attest(ctx, req.(*MsgAttest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DefineResolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDefineResolver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DefineResolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.data.v1.Msg/DefineResolver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DefineResolver(ctx, req.(*MsgDefineResolver))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterResolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterResolver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterResolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.data.v1.Msg/RegisterResolver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterResolver(ctx, req.(*MsgRegisterResolver))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "regen.data.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Anchor",
			Handler:    _Msg_Anchor_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _Msg_Attest_Handler,
		},
		{
			MethodName: "DefineResolver",
			Handler:    _Msg_DefineResolver_Handler,
		},
		{
			MethodName: "RegisterResolver",
			Handler:    _Msg_RegisterResolver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regen/data/v1/tx.proto",
}

func (m *MsgAnchor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Hash != nil {
		{
			size, err := m.Hash.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAnchorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != nil {
		{
			size, err := m.Timestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Iri) > 0 {
		i -= len(m.Iri)
		copy(dAtA[i:], m.Iri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Iri)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hashes) > 0 {
		for iNdEx := len(m.Hashes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Hashes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Attestor) > 0 {
		i -= len(m.Attestor)
		copy(dAtA[i:], m.Attestor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Attestor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewEntries) > 0 {
		for iNdEx := len(m.NewEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MsgDefineResolver) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDefineResolver) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDefineResolver) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResolverUrl) > 0 {
		i -= len(m.ResolverUrl)
		copy(dAtA[i:], m.ResolverUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ResolverUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Manager) > 0 {
		i -= len(m.Manager)
		copy(dAtA[i:], m.Manager)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Manager)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDefineResolverResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDefineResolverResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDefineResolverResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolverId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ResolverId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterResolver) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterResolver) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterResolver) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Data[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ResolverId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ResolverId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Manager) > 0 {
		i -= len(m.Manager)
		copy(dAtA[i:], m.Manager)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Manager)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterResolverResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterResolverResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterResolverResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAnchor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Hash != nil {
		l = m.Hash.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAnchorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Iri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAttest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Attestor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Hashes) > 0 {
		for _, e := range m.Hashes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAttestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NewEntries) > 0 {
		for _, e := range m.NewEntries {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgDefineResolver) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Manager)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ResolverUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDefineResolverResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ResolverId != 0 {
		n += 1 + sovTx(uint64(m.ResolverId))
	}
	return n
}

func (m *MsgRegisterResolver) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Manager)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ResolverId != 0 {
		n += 1 + sovTx(uint64(m.ResolverId))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRegisterResolverResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAnchor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Hash == nil {
				m.Hash = &ContentHash{}
			}
			if err := m.Hash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAnchorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Iri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &types.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashes = append(m.Hashes, &ContentHash_Graph{})
			if err := m.Hashes[len(m.Hashes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewEntries = append(m.NewEntries, &AttestorEntry{})
			if err := m.NewEntries[len(m.NewEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDefineResolver) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDefineResolver: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDefineResolver: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Manager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Manager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolverUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResolverUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDefineResolverResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDefineResolverResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDefineResolverResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolverId", wireType)
			}
			m.ResolverId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolverId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterResolver) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterResolver: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterResolver: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Manager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Manager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolverId", wireType)
			}
			m.ResolverId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolverId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &ContentHash{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterResolverResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterResolverResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterResolverResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
