* Ecological State Verification Methodology
** The rule is that a user should first make a claim about their ecological state and request verification of that claim. If the claim cannot be verified, as far as the system is concerned they are essentially making a false claim and will lose reputation and possibly a posted bond
** A satellite verification algorithm is recommended for all verification protocols as a baseline 
** An audit is automatically triggered whenever a satellite verification algorithm hits a failure or alert condition
** All data matching a certain query from requesting users, that they have stamped on the blockchain for the given site, plus some (can present data from other users regarding the site but it isn't assumed that the requesting user has access to all data about the site - byzantine data could be submitted that they don't actually have access to)
** User submitted data should be passed through an anamoly detector, which may trigger an audit
** If the user submitting data has no successful history of passing audits (i.e. a low reputation score), an audit may be triggered before allowing user submitted data to be considered
** Algorithms will be run on user submitted data and if the data analysis isn't consistent with the submitted claim, an audit will be triggered
** Audits will also happen randomly using the hash of some block in the future as the seed for the random number generator
** If an audit is triggered, but the user requesting claim verification fails to allow the audit to proceed, reputation and the bond amount are automatically lost
** A protocol should specify the procedure for doing an audit for each type of failure condition that can be encountered. This will essentially result in a questionairre or series of questionairres that an auditor is supposed to fill out, schedules regarding when these should be filled out, queries regarding data that needs to be disclosed to the auditor, and logic that is run against the completed questionairres to assess whether or not the audit resulted in success or failure
** Audit failure may either be punitive or non-punitive. Non-punitive failure means that the auditor can't find any intentional misrepresentation of facts, but that operator error resulted in a claim being made that was unsubstantied. Punitive failure means that the auditor discovered evidence of misrepresentation of facts and results in bonds and reputation being lost
** Auditing may be both physical in person site visits and manual review of submitted data, such as photographs
