name: Lint

# **What it does**: Runs go linter when go files have been modified
# and proto linters when proto files have been modified.
#
# **Why we have it**: Ensures all go files and proto files are
# properly formatted according to lint configuration files.
#
# **What does it impact**: Code cleanliness.

on:
  pull_request:
  push:
    branches:
      - main
      - release/v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["app", "types", "x/data", "x/ecocredit"]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: get-diff-app
        with:
          PATTERNS: app/**/**.go
        if: matrix.module == 'app'
      - uses: technote-space/get-diff-action@v6
        id: get-diff-types
        with:
          PATTERNS: types/**/**.go
        if: matrix.module == 'types'
      - uses: technote-space/get-diff-action@v6
        id: get-diff-data
        with:
          PATTERNS: x/data/**/**.go
        if: matrix.module == 'x/data'
      - uses: technote-space/get-diff-action@v6
        id: get-diff-ecocredit
        with:
          PATTERNS: x/ecocredit/**/**.go
        if: matrix.module == 'x/ecocredit'
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "/"
        if: steps.get-diff-app.outputs.diff
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "/types"
        if: steps.get-diff-types.outputs.diff
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "/x/data"
        if: steps.get-diff-data.outputs.diff
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "/x/ecocredit"
        if: steps.get-diff-ecocredit.outputs.diff

  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: git_diff
        with:
          PATTERNS: |
            **/**.proto
      - uses: bufbuild/buf-setup-action@v1
        if: env.GIT_DIFF
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
        if: env.GIT_DIFF

  protolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.proto
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - name: Run protolint
        run: |
          go install github.com/yoheimuta/protolint/cmd/protolint@latest
          protolint .
        if: env.GIT_DIFF
