name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=tab
          skip-go-installation: true
        if: env.GIT_DIFF

  proto-lint:
    name: proto-lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
#      - uses: technote-space/get-diff-action@v6
#        with:
#          PATTERNS: |
#            **/**.proto
      - uses: yoheimuta/action-protolint@v1
#        if: env.GIT_DIFF
