name: Lint

# **What it does**: Runs go linters when go files have been and
# proto linters when proto files have been modified.
#
# **Why we have it**: Ensures all go files and proto files are
# properly formatted according to lint configuration files.
#
# **What does it impact**: Code cleanliness.

on:
  pull_request:
  push:
    branches:
      - master
      - release/v*

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=tab
        if: env.GIT_DIFF

  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.proto
      - uses: bufbuild/buf-setup-action@v1
        if: env.GIT_DIFF
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
        if: env.GIT_DIFF

  protolint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.proto
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - name: protolint
        run: |
          go install github.com/yoheimuta/protolint/cmd/protolint@latest
          protolint .
        if: env.GIT_DIFF
