name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - release/v*

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=tab
          skip-go-installation: true
        if: env.GIT_DIFF

  protolint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
#      - uses: technote-space/get-diff-action@v6
#        with:
#          PATTERNS: |
#            **/**.proto
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
#        if: env.GIT_DIFF
      - name: Install protolint
        run: go install github.com/yoheimuta/protolint/cmd/protolint@latest
#        if: env.GIT_DIFF
      - name: Run protolint
        run: protolint .
#        if: env.GIT_DIFF
