name: Packages

# This workflow should always match the "Release" workflow aside
# from when this workflow is triggered and what arguments are passed
# to goreleaser/goreleaser-action@v2 in the "Run GoReleaser" step.

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: GCC multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib clang
      -
        name: OSXCross for CGO Support
        run: |
          mkdir /home/runner/work/osxcross
          git clone https://github.com/likhita-809/osxcross-target.git /home/runner/work/osxcross/target
          sudo ln -s /home/runner/work/osxcross/target/target/lib/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
      -
        name: LibWasm for CosmWasm Support
        run: |
          curl -o /home/runner/work/libwasmvm_muslc.a -L https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0-beta5/libwasmvm_muslc.a
          sha256sum /home/runner/work/libwasmvm_muslc.a | grep d16a2cab22c75dbe8af32265b9346c6266070bdcf9ed5aa9b7b39a7e32e25fe0
          sudo ln -s /home/runner/work/libwasmvm_muslc.a /usr/lib/libwasmvm_muslc.a
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --skip-validate --rm-dist
