name: Proto

# **What it does**: Checks for breaking changes in proto files
# when proto files have been modified.
#
# **Why we have it**: Provides visibility into breaking changes and
# ensures no breaking changes are merged to a release branch.
#
# **What does it impact**: Application release process.

on:
  pull_request:
    branches:
      - main
      - release/v*
    paths:
      - 'proto/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  break-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=proto'
  
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-setup-action@v1.50.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"

  protolint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        id: git-diff-proto
        with:
          PATTERNS: |
            **/**.proto
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
        if: steps.git-diff-proto.outputs.diff
      - name: Run protolint
        run: |
          go install github.com/yoheimuta/protolint/cmd/protolint@latest
          protolint .
        if: steps.git-diff-proto.outputs.diff
