name: Release

# **What it does**: Runs the goreleaser release process when a new
# version of the application is tagged and pushed.
#
# **Why we have it**: Automates the release process.
#
# **What does it impact**: Application release process.

on:
  push:
    tags:
      - v*

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for docker/setup-buildx-action to create a GitHub release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish release
        run: |
          sudo rm -rf dist
          make release
        env:
          GORELEASER_RELEASE: true
          IS_STABLE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
