name: Release

# **What it does**: Runs the goreleaser release process when a new
# version of the application is tagged and pushed.
#
# **Why we have it**: Automates the release process.
#
# **What does it impact**: Application release process.

on:
  push:
    tags:
      - v*

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for docker/setup-buildx-action to create a GitHub release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
<<<<<<< HEAD
      - name: Run release setup
        run: ./scripts/release-setup.sh
        shell: bash
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
=======
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish release
        run: |
          sudo rm -rf dist
          make release
>>>>>>> fdd4424d (ci(build): migrate goreleaser setup to use goreleaser-cross (#1733))
        env:
          GORELEASER_RELEASE: true
          IS_STABLE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
