name: Release

# **What it does**: Runs the goreleaser release process when a new
# version of the application is tagged and pushed.
#
# **Why we have it**: Automates the release process.
#
# **What does it impact**: Application release process.

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run release setup
        run: ./scripts/release-setup.sh
        shell: bash
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
