name: Release

# **What it does**: Runs the goreleaser release process when a new
# version of the application is tagged and pushed.
#
# **Why we have it**: Automates the release process.
#
# **What does it impact**: Application release process.

on:
  push:
    tags:
      - v*

permissions:
  contents: read

before:
  hooks:
    - ./scripts/completions.sh

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*

# brews:
#   - install: |-
#       bin.install "regen"
#       bash_completion.install "completions/regen.bash" => "regen"
#       zsh_completion.install "completions/regen.zsh" => "_regen"
#       fish_completion.install "completions/regen.fish"  

nfpms:
  - contents:
      - src: ./completions/regen.bash
        dst: /usr/share/bash-completion/completions/regen
        file_info:
          mode: 0644
      - src: ./completions/regen.fish
        dst: /usr/share/fish/vendor_completions.d/regen.fish
        file_info:
          mode: 0644
      - src: ./completions/regen.zsh
        dst:  /usr/share/zsh/vendor-completions/_regen
        file_info:
          mode: 0644

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run release setup
        run: ./scripts/release-setup.sh
        shell: bash
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
