name: Sims Nightly

# **What it does**: Runs simulations (after-import, fast) on a
# set schedule.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  schedule:
    # Runs "at 1am every day"
    - cron: "0 0 * * *"

jobs:
  sim-after-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run sim-after-import
        run: make sim-regen-after-import

  sim-fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run sim-fast
        run: make sim-regen-fast
