name: Sims

# **What it does**: Runs simulations (nondeterminism, import-export)
# when go files have been modified.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  pull_request:
  push:
    branches:
      - master
      - release/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: make build

  install-runsim:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@latest
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: Run sim-nondeterminism
        run: make sim-regen-nondeterminism
        if: env.GIT_DIFF

  sim-import-export:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: Run sim-import-export
        run: make sim-regen-import-export
        if: env.GIT_DIFF
