name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    name: Sub modules test and code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run sub-modules test and codecov
        run: make test-cover
        if: env.GIT_DIFF
      - name: Upload codecov report
        uses: codecov/codecov-action@v1
        with:
          flags: ${{matrix.envs}}
          file: coverage.txt
        if: env.GIT_DIFF

  liveness-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: start localnet
        run: |
          make clean localnet-start
        if: env.GIT_DIFF
      - name: test liveness
        run: |
          ./contrib/localnet_liveness.sh 100 5 50 localhost
        if: env.GIT_DIFF