name: Tests

# **What it does**: Runs unit and integration tests when go files
# have been modified and provides code coverage reports.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  pull_request:
  push:
    branches:
      - main
      - release/v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Sub modules test and code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - name: Run sub-modules test and codecov
        run: make test-cover
        if: env.GIT_DIFF
      - name: Upload codecov report
        uses: codecov/codecov-action@v3
        with:
          flags: ${{matrix.envs}}
          file: coverage.txt
        if: env.GIT_DIFF

  liveness-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
        if: env.GIT_DIFF
      - name: Start localnet
        run: make clean localnet-start
        if: env.GIT_DIFF
      - name: Run liveness test
        run: ./contrib/localnet_liveness.sh 100 5 50 localhost
        if: env.GIT_DIFF
