name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run tests
        run: make test
      - name: run experimental tests
        run: EXPERIMENTAL=true make test
  code_cov:
    name: Cover report
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envs: ["stable-codecov", "experimental-codecov"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set experimental env
        if: matrix.envs == 'experimental-codecov'
        run: export EXPERIMENTAL=true
      - name: run test cover
        run: make test-cover
      - name: Upload codecov report
        uses: codecov/codecov-action@v1.5.0
        with:
          flags: ${{matrix.envs}}
          file: coverage.txt
        if: env.GIT_DIFF
